NetworkTables:
  BlingSelect: /Bling/blingSelect
  TeamColor: /FMSInfo/IsRedAlliance
  stationNumb: /FMSInfo/StationNumber
  chassieSelect: /Bling/chassieSelect
  HostAddress: 192.168.1.148
  TeamNumber: 447
  Deployed: True
LoopDelay: 0.001
  